FROM node:14-alpine AS builder
RUN apk --update add git openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

ENV NODE_ENV development
WORKDIR /usr/src/app
COPY package.json .
RUN yarn install
COPY . .
RUN yarn build 

FROM nginx:1.18-alpine

COPY --from=builder /usr/src/app/build /var/www/html
COPY /nginx/nginx.conf /etc/nginx/nginx.conf
COPY /https/ /etc/ssl/met/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]